apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway-pod
        image: us-docker.pkg.dev/boxwood-mantra-442011-a2/gcr.io/cifar10-gateway-app:1
        resources:
          limits:
            memory: "512Mi"
            cpu: "0.2"
        ports:
        - containerPort: 80
        env: 
          - name: MODEL_SERVING_HOST
            value: http://model-service.default.svc.cluster.local:8500/predictions/cifar10-classifier
