apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
      - name: model-pod
        image: us-docker.pkg.dev/boxwood-mantra-442011-a2/gcr.io/cifar10-gateway-app-torchserve:1
        resources:
          limits:
            memory: "2.5Gi"
            cpu: "1.0"
        ports:
        - containerPort: 8080
