apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
      - name: model-pod
        image: cifar10-classifier-torchserve:v001
        resources:
          limits:
            memory: "2.5Gi"
            cpu: "1.0"
        ports:
        - containerPort: 8080
